# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f234ea23fa7bd1c1ef09180994493bd2b7e2e7ea12f1af4782816eddb769a05df7404c50551d4722c5e23370fb5ecfc175adbf645b47347c7973a66280bf3895

test:
  secret_key_base: 87d6944264b711bd5bab63073c29c16d4922b7e7c7c53dbabce53d7039bb56c0ba774add067469b3d6397a1345017c1570486161f8685651628079d921885f06

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
